/**
 * Comprehensive list of countries with their names, ISO codes, and dial codes.
 * Used for the searchable dropdown in the Contact Modal.
 */
export const countries = [
  { name: 'Afghanistan', code: 'af', dialCode: '+93' },
  { name: 'Albania', code: 'al', dialCode: '+355' },
  { name: 'Algeria', code: 'dz', dialCode: '+213' },
  { name: 'Andorra', code: 'ad', dialCode: '+376' },
  { name: 'Angola', code: 'ao', dialCode: '+244' },
  { name: 'Argentina', code: 'ar', dialCode: '+54' },
  { name: 'Australia', code: 'au', dialCode: '+61' },
  { name: 'Austria', code: 'at', dialCode: '+43' },
  { name: 'Bahrain', code: 'bh', dialCode: '+973' },
  { name: 'Bangladesh', code: 'bd', dialCode: '+880' },
  { name: 'Belgium', code: 'be', dialCode: '+32' },
  { name: 'Brazil', code: 'br', dialCode: '+55' },
  { name: 'Canada', code: 'ca', dialCode: '+1' },
  { name: 'Chile', code: 'cl', dialCode: '+56' },
  { name: 'China', code: 'cn', dialCode: '+86' },
  { name: 'Colombia', code: 'co', dialCode: '+57' },
  { name: 'Denmark', code: 'dk', dialCode: '+45' },
  { name: 'Egypt', code: 'eg', dialCode: '+20' },
  { name: 'Finland', code: 'fi', dialCode: '+358' },
  { name: 'France', code: 'fr', dialCode: '+33' },
  { name: 'Germany', code: 'de', dialCode: '+49' },
  { name: 'Greece', code: 'gr', dialCode: '+30' },
  { name: 'Hong Kong', code: 'hk', dialCode: '+852' },
  { name: 'Hungary', code: 'hu', dialCode: '+36' },
  { name: 'Iceland', code: 'is', dialCode: '+354' },
  { name: 'India', code: 'in', dialCode: '+91' },
  { name: 'Indonesia', code: 'id', dialCode: '+62' },
  { name: 'Iran', code: 'ir', dialCode: '+98' },
  { name: 'Iraq', code: 'iq', dialCode: '+964' },
  { name: 'Ireland', code: 'ie', dialCode: '+353' },
  { name: 'Israel', code: 'il', dialCode: '+972' },
  { name: 'Italy', code: 'it', dialCode: '+39' },
  { name: 'Japan', code: 'jp', dialCode: '+81' },
  { name: 'Jordan', code: 'jo', dialCode: '+962' },
  { name: 'Kenya', code: 'ke', dialCode: '+254' },
  { name: 'Kuwait', code: 'kw', dialCode: '+965' },
  { name: 'Malaysia', code: 'my', dialCode: '+60' },
  { name: 'Mexico', code: 'mx', dialCode: '+52' },
  { name: 'Netherlands', code: 'nl', dialCode: '+31' },
  { name: 'New Zealand', code: 'nz', dialCode: '+64' },
  { name: 'Norway', code: 'no', dialCode: '+47' },
  { name: 'Oman', code: 'om', dialCode: '+968' },
  { name: 'Pakistan', code: 'pk', dialCode: '+92' },
  { name: 'Philippines', code: 'ph', dialCode: '+63' },
  { name: 'Poland', code: 'pl', dialCode: '+48' },
  { name: 'Portugal', code: 'pt', dialCode: '+351' },
  { name: 'Qatar', code: 'qa', dialCode: '+974' },
  { name: 'Russia', code: 'ru', dialCode: '+7' },
  { name: 'Saudi Arabia', code: 'sa', dialCode: '+966' },
  { name: 'Singapore', code: 'sg', dialCode: '+65' },
  { name: 'South Africa', code: 'za', dialCode: '+27' },
  { name: 'South Korea', code: 'kr', dialCode: '+82' },
  { name: 'Spain', code: 'es', dialCode: '+34' },
  { name: 'Sri Lanka', code: 'lk', dialCode: '+94' },
  { name: 'Sweden', code: 'se', dialCode: '+46' },
  { name: 'Switzerland', code: 'ch', dialCode: '+41' },
  { name: 'Thailand', code: 'th', dialCode: '+66' },
  { name: 'Turkey', code: 'tr', dialCode: '+90' },
  { name: 'Ukraine', code: 'ua', dialCode: '+380' },
  { name: 'United Arab Emirates', code: 'ae', dialCode: '+971' },
  { name: 'United Kingdom', code: 'gb', dialCode: '+44' },
  { name: 'United States', code: 'us', dialCode: '+1' },
  { name: 'Vietnam', code: 'vn', dialCode: '+84' },
];
